### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by amirouche** [amirouche/easy-conceptnet#1]
- [ ] :cake: tsv parser
- [ ] :house: load into nstore
- [ ] :confetti_ball: guess wiredtiger configuration (eviction and memory)
- [ ] :abcd: fuzzy search
- [ ] :boat: REST HTTP interface

**Comment by amirouche** [comment]
# easy-concepnet

## What?

`easy-conceptnet` is database with an HTTP server that can host conceptnet data. It is meant to be easy to use and performant.

## Why?

I want to make conceptnet more accessible.

## How?

It rely on Scheme programming language and wiredtiger database library. To use you only to unzip the release build.

## Documentation

### Python API

TODO

### HTTP REST

#### `/api/`

```
   ___  __ _ ___ _   _                              
  / _ \/ _` / __| | | |                             
 |  __/ (_| \__ \ |_| |                             
  \___|\__,_|___/\__, |          _              _   
                  __/ |         | |            | |  
   ___ ___  _ __ |___/ ___ _ __ | |_ _ __   ___| |_ 
  / __/ _ \| '_ \ / __/ _ \ '_ \| __| '_ \ / _ \ __|
 | (_| (_) | | | | (_|  __/ |_) | |_| | | |  __/ |_ 
  \___\___/|_| |_|\___\___| .__/ \__|_| |_|\___|\__|
                          | |                       
                          |_|                       

You know for conceptnet.io

version: 0.0.0
```

#### `/api/concept/{{ lang }}/{{ name }}/{{ kind }}/?skip=XX&limit=YY`
#### `/api/concept/{{ lang }}/{{ name }}/{{ kind }}/summary/`
#### `/api/concept/{{ lang }}/{{ name }}/{{ kind }}/count/`
#### `/api/concept/{{ lang }}/{{ name }}/{{ kind }}/relation/{{ relation }}/`
#### `/api/concept/fuzzy-search/?query=ABCDEF`
#### `/api/concept/search/?ABC=DEF&UVW=XYZ`
